FROM arm32v6/node:8.9.1-alpine

LABEL maintainer "Michael Tarleton<michael.tarleton@me.com>"

EXPOSE 80 443

WORKDIR "/home/node"

# Add packages
RUN apk update \
    && apk --no-cache add \
        git \
    && rm -rf /var/cache/apk/*

# Add the package.json
ADD [ "package*.json", "./" ]

# Install node modules
RUN npm install --silent --production

# Copy entire app
ADD src/ ./src

# Run the app
ENTRYPOINT [ "npm", "start" ]